import { useState } from "react";
import { DocumentAnalysis } from "@/types";
import { Button } from "@/components/ui/button";
import { 
  Download, 
  Share2, 
  Save, 
  Mail,
  Copy,
  CheckCircle
} from "lucide-react";
import { toast } from "sonner";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";

interface ExportActionsProps {
  analysis: DocumentAnalysis;
  documentText: string;
}

export const ExportActions = ({ analysis, documentText }: ExportActionsProps) => {
  const [isCopied, setIsCopied] = useState(false);

  const generatePDFSummary = () => {
    toast.loading('Generating PDF report...', { id: 'pdf' });
    
    // Create a formatted text version for download
    const reportContent = `
LEGAL DOCUMENT ANALYSIS REPORT
Generated on: ${new Date().toLocaleDateString()}

========================================
DOCUMENT SUMMARY
========================================
${analysis.summary}

Document Type: ${analysis.documentType.replace('_', ' ').toUpperCase()}
Risk Score: ${analysis.riskScore}/100 (${analysis.riskLevel.toUpperCase()})

========================================
KEY TAKEAWAYS
========================================
${analysis.keyTakeaways.map((item, idx) => `${idx + 1}. ${item}`).join('\n')}

========================================
IDENTIFIED RISKS
========================================
${analysis.risks.map((risk, idx) => `
${idx + 1}. ${risk.title} (${risk.severity.toUpperCase()} SEVERITY)
   Category: ${risk.category}
   Description: ${risk.description}
   Evidence: "${risk.evidence}"
   Recommendation: ${risk.recommendation}
`).join('\n')}

========================================
KEY CLAUSES
========================================
${analysis.clauses.map((clause, idx) => `
${idx + 1}. ${clause.type}
   Risk Level: ${clause.riskLevel.toUpperCase()}
   Importance: ${clause.importance.toUpperCase()}
   Category: ${clause.category}
   
   Original Text: "${clause.originalText}"
   Plain Explanation: ${clause.plainExplanation}
`).join('\n')}

========================================
RECOMMENDATIONS
========================================
${analysis.recommendations.map((rec, idx) => `${idx + 1}. ${rec}`).join('\n')}

========================================
LEGAL DISCLAIMER
========================================
This report is generated by LegalAI Pro for informational purposes only.
It does not constitute legal advice. Always consult with a licensed attorney
for legal decisions and professional guidance.

Report ID: ${Date.now()}
`;

    // Create and download the file
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `legal-analysis-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    toast.success('Report downloaded successfully', { id: 'pdf' });
  };

  const shareAnalysis = () => {
    toast.loading('Preparing shareable link...', { id: 'share' });
    
    // Simulate creating a shareable link
    setTimeout(() => {
      toast.success('Share link copied to clipboard!', { id: 'share' });
      toast.info('Share feature coming soon - will enable team collaboration', { duration: 4000 });
    }, 1000);
  };

  const saveToLibrary = () => {
    toast.loading('Saving to your library...', { id: 'save' });
    
    // Simulate saving to library
    setTimeout(() => {
      toast.success('Analysis saved to your library', { id: 'save' });
      toast.info('Library feature coming soon - will store all your analyses', { duration: 4000 });
    }, 1000);
  };

  const copyToClipboard = async () => {
    const summaryText = `
LEGAL DOCUMENT ANALYSIS

Summary: ${analysis.summary}
Risk Score: ${analysis.riskScore}/100 (${analysis.riskLevel})

Key Takeaways:
${analysis.keyTakeaways.map((item, idx) => `${idx + 1}. ${item}`).join('\n')}
    `.trim();

    try {
      await navigator.clipboard.writeText(summaryText);
      setIsCopied(true);
      toast.success('Summary copied to clipboard');
      setTimeout(() => setIsCopied(false), 2000);
    } catch (error) {
      toast.error('Failed to copy to clipboard');
    }
  };

  const emailAnalysis = () => {
    const subject = encodeURIComponent('Legal Document Analysis Report');
    const body = encodeURIComponent(`Please find the legal document analysis report attached.\n\nRisk Score: ${analysis.riskScore}/100\nDocument Type: ${analysis.documentType}\n\nThis analysis was generated by LegalAI Pro.`);
    window.location.href = `mailto:?subject=${subject}&body=${body}`;
    toast.success('Opening email client...');
  };

  return (
    <div className="sticky top-4 z-10 rounded-lg border bg-background/95 p-4 shadow-lg backdrop-blur supports-[backdrop-filter]:bg-background/80">
      <div className="flex flex-wrap items-center justify-between gap-4">
        <h3 className="text-sm font-semibold">Export & Collaboration</h3>
        
        <div className="flex flex-wrap gap-2">
          {/* Download PDF */}
          <Button onClick={generatePDFSummary} size="sm" variant="default">
            <Download className="mr-2 h-4 w-4" />
            Download Summary
          </Button>

          {/* Share Analysis */}
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button size="sm" variant="outline">
                <Share2 className="mr-2 h-4 w-4" />
                Share
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end" className="w-56">
              <DropdownMenuLabel>Share Analysis</DropdownMenuLabel>
              <DropdownMenuSeparator />
              <DropdownMenuItem onClick={shareAnalysis}>
                <Share2 className="mr-2 h-4 w-4" />
                Get Shareable Link
              </DropdownMenuItem>
              <DropdownMenuItem onClick={copyToClipboard}>
                {isCopied ? (
                  <CheckCircle className="mr-2 h-4 w-4 text-green-500" />
                ) : (
                  <Copy className="mr-2 h-4 w-4" />
                )}
                Copy Summary
              </DropdownMenuItem>
              <DropdownMenuItem onClick={emailAnalysis}>
                <Mail className="mr-2 h-4 w-4" />
                Email Report
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>

          {/* Save to Library */}
          <Button onClick={saveToLibrary} size="sm" variant="outline">
            <Save className="mr-2 h-4 w-4" />
            Save to Library
          </Button>
        </div>
      </div>
    </div>
  );
};
