import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { documentText, fileName, language } = await req.json();
    
    if (!documentText || !fileName) {
      return new Response(
        JSON.stringify({ error: 'Document text and file name are required' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const GEMINI_API_KEY = Deno.env.get('GEMINI_API_KEY');
    const GOOGLE_TRANSLATE_API_KEY = Deno.env.get('GOOGLE_TRANSLATE_API_KEY');
    
    if (!GEMINI_API_KEY) {
      console.error('GEMINI_API_KEY is not configured');
      return new Response(
        JSON.stringify({ error: 'API key not configured' }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Translate to English if needed (supports Hindi, Gujarati)
    let translatedText = documentText;
    let detectedLanguage = language || 'en';
    
    if (GOOGLE_TRANSLATE_API_KEY && language && language !== 'en') {
      console.log(`Translating document from ${language} to English...`);
      
      try {
        const translateResponse = await fetch(
          `https://translation.googleapis.com/language/translate/v2?key=${GOOGLE_TRANSLATE_API_KEY}`,
          {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
            },
            body: JSON.stringify({
              q: documentText,
              source: language,
              target: 'en',
              format: 'text'
            }),
          }
        );

        if (translateResponse.ok) {
          const translateData = await translateResponse.json();
          translatedText = translateData.data.translations[0].translatedText;
          console.log('Translation successful');
        } else {
          console.error('Translation failed, proceeding with original text');
        }
      } catch (translateError) {
        console.error('Translation error:', translateError);
        // Continue with original text if translation fails
      }
    }

    // Call Gemini API for document analysis
    const prompt = `You are a legal document analysis AI. Analyze the following document and provide:

1. Overall Risk Score (0-100, where 100 is highest risk)
2. Executive Summary (2-3 sentences)
3. Key Risk Findings (list major concerns)
4. Compliance Issues (if any)
5. Recommendations (actionable advice)

Document: ${fileName}
${language !== 'en' ? `Original Language: ${language}\n` : ''}Content: ${translatedText}

Provide your analysis in JSON format with these fields:
{
  "overallRiskScore": number,
  "executiveSummary": string,
  "keyFindings": string[],
  "complianceIssues": string[],
  "recommendations": string[]
}`;

    console.log('Calling Gemini API for document analysis...');
    
    // Use a low temperature to make the model output more deterministic for structured JSON
    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:generateContent?key=${GEMINI_API_KEY}`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          contents: [{
            parts: [{ text: prompt }]
          }],
          generationConfig: {
            // reduce randomness to encourage consistent JSON outputs
            temperature: 0.0,
            topK: 1,
            topP: 0.8,
            maxOutputTokens: 2048,
          }
        }),
      }
    );

    if (!response.ok) {
      const errorText = await response.text();
      console.error('Gemini API error:', response.status, errorText);
      return new Response(
        JSON.stringify({ error: 'Failed to analyze document', details: errorText }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const data = await response.json();
    console.log('Gemini API response received');

    // Extract the generated text
    const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text;
    
    if (!generatedText) {
      console.error('No text generated by Gemini');
      return new Response(
        JSON.stringify({ error: 'No analysis generated' }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Try to parse the JSON response robustly
    let analysisResult: any = null;
    try {
      // Attempt to extract first {...} JSON object block from the generated text
      const cleanedText = generatedText.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim();

      // Find the first JSON object boundaries
      const firstBrace = cleanedText.indexOf('{');
      const lastBrace = cleanedText.lastIndexOf('}');
      let jsonText = cleanedText;

      if (firstBrace !== -1 && lastBrace !== -1 && lastBrace > firstBrace) {
        jsonText = cleanedText.substring(firstBrace, lastBrace + 1);
      }

      analysisResult = JSON.parse(jsonText);
    } catch (e) {
      console.error('Failed to parse Gemini response as JSON:', e);
      // As a better fallback than a constant score, derive a simple heuristic based on keywords
      const riskKeywords = ['breach', 'penalty', 'liability', 'indemnify', 'terminate', 'unfair', 'unenforceable', 'fine', 'damages', 'default', 'penalties'];
      const lowered = generatedText.toLowerCase();
      let matches = 0;
      for (const kw of riskKeywords) {
        if (lowered.includes(kw)) matches += 1;
      }

      // Heuristic mapping: base 20 + 15 per matched keyword, capped at 95
      const heuristicScore = Math.min(95, 20 + matches * 15);

      analysisResult = {
        overallRiskScore: heuristicScore,
        executiveSummary: generatedText.substring(0, 500),
        keyFindings: [],
        complianceIssues: [],
        recommendations: []
      };
    }

    console.log('Analysis complete');
    
    return new Response(
      JSON.stringify(analysisResult),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error) {
    console.error('Error in analyze-document function:', error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : 'Unknown error' }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
